name: kufta_percha
description: "Nueva era de organizaci√≥n de percha."
publish_to: "none"
version: 1.1.0+2

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  permission_handler: ^12.0.1
  image_picker: ^1.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  flutter_local_notifications: ^19.5.0

  # Splash screen native
  flutter_native_splash: ^2.4.7
  # Iconos recientes de google fonts
  material_symbols_icons: ^4.2906.0
  # Assets de lottie files
  lottie: ^3.3.2


  flutter_localizations:
    sdk: flutter
  device_info_plus: ^12.3.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/img/
    - assets/gifts/

  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka.ttf
